---
abstract: 'A specialized ElasticSearch client.'
author:
  - '=over 4'
build_requires:
  Test::More: 0.9
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v1.0.0, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Elastijk
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Elastijk:
    file: lib/Elastijk.pm
    version: 0.07
  Elastijk::oo:
    file: lib/Elastijk/oo.pm
    version: 0
requires:
  Hijk: 0.09
  JSON: 2.59
resources:
  bugtracker: https://github.com/gugod/Elastijk/issues
  homepage: https://github.com/gugod/Elastijk
  repository: git://github.com/gugod/Elastijk.git
version: 0.07
x_authority: cpan:GUGOD
x_contributors:
  - 'borislav nikolov <jack@sofialondonmoskva.com>'
  - 'Kang-min Liu <gugod@gugod.org>'
